export const getControls = () => ([{
    propertyName: 'textBox',
    inputType: 'textBox',
    displayName: 'TextBox',
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'textArea',
    inputType: 'textArea',
    displayName: 'TextArea',
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'selectBox',
    inputType: 'selectBox',
    displayName: 'SelectBox',
    inputArray: [],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'datebox',
    inputType: 'dateBox',
    displayName: 'DateBox',
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'toggle',
    inputType: 'toggle',
    displayName: 'Toggle',
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'checkBox',
    inputType: 'checkBox',
    displayName: 'CheckBox',
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'radioButton',
    inputType: 'radioButton',
    displayName: 'RadioButton',
    inputArray: ['Option 1', 'Option 2'],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  },
  {
    propertyName: 'multiSelect',
    inputType: 'multiSelect',
    displayName: 'MultiSelect',
    inputArray: ['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5'],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false,
    requiredValidationMessage: null
  }]);

