export const getControls = () => ([{
    propertyName: 'textBox',
    inputType: 'textBox',
    displayName: null,
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'textArea',
    inputType: 'textArea',
    displayName: null,
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'selectBox',
    inputType: 'selectBox',
    displayName: null,
    inputArray: [],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'datebox',
    inputType: 'dateBox',
    displayName: null,
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'toggle',
    inputType: 'toggle',
    displayName: null,
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'checkBox',
    inputType: 'checkBox',
    displayName: null,
    inputArray: null,
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'radioButton',
    inputType: 'radioButton',
    displayName: null,
    inputArray: ['Option 1', 'Option 2'],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  },
  {
    propertyName: 'multiSelect',
    inputType: 'multiSelect',
    displayName: null,
    inputArray: ['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5'],
    valueField: null,
    displayField: null,
    required: true,
    openSettings: false,
    selected: false,
    isFormControlOnly: false
  }]);

